Repository pie-sfac/1-13-pongDangPong, pull requests merged in 2023-08, with the labels that each got.

#49 [✨feat] 회원 수강권 부여, 수강권 수정 기능구현
  src/app/App.tsx
  src/components/center/ticket/TicketItem.tsx
  src/components/center/ticket/TicketList.tsx
  src/components/header/subHeader.tsx
  src/components/members/Members.tsx
  src/components/members/MembersAddTicekt.tsx
  src/components/members/MembersAlbum.tsx
  src/components/members/MembersDetail.tsx
  src/components/members/MembersRecord.tsx
  src/components/members/MembersRegister.tsx
  src/data/menuData.ts
  src/pages/CreateSchedule.tsx
  src/pages/MembersDetail.tsx
  src/styles/styles.tsx
Labels: ✨ Feature

#50 [✨feat] 일정조회 캘린더 및 대시보드 기능 구현
  package-lock.json
  package.json
  src/apis/schedulesAPIs.tsx
  src/apis/ticketsAPIs.tsx
  src/app/App.tsx
  src/assets/icons/schedules/calendar.svg
  src/components/header/GlobalHeader.tsx
  src/components/schedules/Calendar.tsx
  src/components/schedules/Dashboard.tsx
  src/components/schedules/SchedulesList.tsx
  src/components/schedules/utils/filterAndSortSchedulesByDate.tsx
  src/components/schedules/utils/generateCalendar.tsx
  src/components/schedules/utils/getDate.tsx
  src/components/schedules/utils/getEventCountbyDate.tsx
  src/data/menuData.ts
  src/pages/Schedules.tsx
  src/stores/menuSlice.tsx
  src/stores/selectedDateSlice.tsx
  src/stores/store.tsx
  src/styles/styles.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#52 [💄style] 로그인, 일정생성 페이지 스타일링
  src/assets/icons/Profile.svg
  src/components/schedule/CreateCounseling.tsx
  src/components/schedule/CreateSchedule.tsx
  src/components/schedule/ScheduleModal.tsx
  src/data/menuData.ts
  src/pages/CreateCounseling.tsx
  src/pages/CreateSchedule.tsx
  src/pages/Login.tsx
  src/pages/Schedule.tsx
  src/styles/loginStyle.tsx
Labels: 🌈 Style

#54 [🐞fix] 센터관리 티켓 컴포넌트 원복
  src/components/center/ticket/TicketItem.tsx
  src/styles/styles.tsx
Labels: 🐞 BugFix

#56 [💄style] 수강권 컴포넌트 교체 및 수정
  src/assets/icons/editicon.svg
  src/assets/icons/indexIcons.tsx
  src/components/members/Members.tsx
  src/components/members/MembersDetail.tsx
  src/components/members/ticket/TicketItem.tsx
  src/data/menuData.ts
Labels: 🌈 Style

#70 [✨feat] 수강권 일시중단, 일시중단 해제, 환불 기능 및 분류 기능
  src/assets/icons/indexIcons.tsx
  src/components/common/Modal.tsx
  src/components/header/subHeader.tsx
  src/components/members/Members.tsx
  src/components/members/MembersAddTicekt.tsx
  src/components/members/MembersDetail.tsx
  src/components/members/MembersRecord.tsx
  src/components/members/MembersRegister.tsx
  src/components/members/ticket/TicketItem.tsx
  src/data/menuData.ts
  src/styles/center/ticketsStyle.tsx
Labels: ✨ Feature

#71 [💄style] 회원 디테일 공통 스타일 틀어진 부분 수정
  src/components/center/ticket/TicketIssued.tsx
  src/components/members/MembersDetail.tsx
Labels: 🌈 Style

#73 [✨feat] 개인 수업 및 상담 일정 기능 개발
  src/apis/schedulesAPIs.tsx
  src/app/routes/PublicRoute.tsx
  src/components/center/staff/StaffsEditModal.tsx
  src/components/center/staff/StaffsForm.tsx
  src/components/center/ticket/Form/SelectField.tsx
  src/components/center/ticket/TicketEditForm.tsx
  src/components/center/ticket/TicketForm.tsx
  src/components/center/ticket/TicketIssued.tsx
  src/components/common/DisabledFindUserButton.tsx
  src/components/common/NoticeModal.tsx
  src/components/schedules/Calendar.tsx
  src/components/schedules/Dashboard.tsx
  src/components/schedules/PrivateForm.tsx
  src/components/schedules/SchedulesHome.tsx
  src/components/schedules/calendar/Calendar.tsx
  src/components/schedules/calendar/Dashboard.tsx
  src/components/schedules/calendar/SchedulesHome.tsx
  src/components/schedules/details/CounselingDetail.tsx
  src/components/schedules/details/CounselingRecordFormModal.tsx
  src/components/schedules/details/MemberCardItem.tsx
  src/components/schedules/details/PrivateLessonDetail.tsx
  src/components/schedules/details/SchedulesCancelModal.tsx
  src/components/schedules/details/StatusButton.tsx
  src/components/schedules/form/BookableTicketsList.tsx
  src/components/schedules/form/CounselingForm.tsx
  src/components/schedules/form/PrivateLessonForm.tsx
  src/components/schedules/form/SchedulesFormModal.tsx
  src/hooks/apis/useSwrData.tsx
  src/hooks/utils/useEditMode.tsx
  src/hooks/utils/useErrorModal.tsx
  src/hooks/utils/useInput.tsx
  src/hooks/utils/useValidation.tsx
  src/pages/Login.tsx
  src/pages/Schedules.tsx
  src/pages/backup/Schedule.tsx
  src/stores/selectedDateSlice.tsx
  src/styles/SchedulesStyle.tsx
  src/styles/center/ticketFormStyle.tsx
  src/styles/styles.tsx
  src/styles/theme.ts
  src/utils/extractBasePath.tsx
  src/utils/filterAndSortSchedulesByDate.tsx
  src/utils/formatTimestamp.tsx
  src/utils/getDate.tsx
  src/utils/getEventCountbyDate.tsx
  src/utils/handleModalNotice.tsx
Labels: ✨ Feature

#76 [♻refactor] 캘린더 및 대시보드 의존성 분리
  src/components/schedules/calendar/Calendar.tsx
  src/components/schedules/calendar/Dashboard.tsx
  src/components/schedules/calendar/SchedulesHome.tsx
  src/components/schedules/details/CounselingDetail.tsx
  src/components/schedules/details/PrivateLessonDetail.tsx
  src/components/schedules/form/CounselingForm.tsx
  src/components/schedules/form/PrivateLessonForm.tsx
  src/hooks/utils/useEventCount.tsx
  src/hooks/utils/useFilterAndSortSchedules.tsx
  src/stores/selectedDateSlice.tsx
  src/utils/filterAndSortSchedulesByDate.tsx
  src/utils/schedules/formatTimestamp.tsx
  src/utils/schedules/generateCalendar.tsx
  src/utils/schedules/getDate.tsx
  src/utils/schedules/getEventCountbyDate.tsx
Labels: 🔨 Refactor

#80 [✨feat] 직원 로그인 기능 추가
  src/apis/authAPIs.tsx
  src/app/App.tsx
  src/components/center/info/CenterInfo.tsx
  src/components/center/staff/StaffsEditModal.tsx
  src/components/center/staff/StaffsForm.tsx
  src/components/center/ticket/Form/TicketFormComponent.tsx
  src/components/center/ticket/TicketList.tsx
  src/components/common/InputField.tsx
  src/components/common/SelectField.tsx
  src/components/header/GlobalHeader.tsx
  src/components/header/subHeader.tsx
  src/components/layout/Layout.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginLayout.tsx
  src/components/members/MembersRegister.tsx
  src/components/schedules/calendar/SchedulesHome.tsx
  src/components/schedules/form/BookableTicketsList.tsx
  src/components/schedules/form/CounselingForm.tsx
  src/hooks/apis/useAuth.tsx
  src/hooks/utils/useInput.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/stores/menuSlice.tsx
  src/stores/tokenSilce.tsx
  src/styles/loginStyle.tsx
  src/styles/styles.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#83 [♻refactor] 다수 기능 코드 보완 및 버그 수정
  src/app/App.tsx
  src/assets/icons/Logo.svg
  src/assets/icons/indexIcons.tsx
  src/components/center/staff/StaffsDetail.tsx
  src/components/center/staff/StaffsEditModal.tsx
  src/components/center/ticket/Form/TicketFormComponent.tsx
  src/components/center/ticket/IssuedTicketModal.tsx
  src/components/center/ticket/TicketEditForm.tsx
  src/components/center/ticket/TicketForm.tsx
  src/components/center/ticket/TicketFormComponent.tsx
  src/components/center/ticket/TicketIssued.tsx
  src/components/common/Button.tsx
  src/components/common/FindUserButton.tsx
  src/components/common/FindUserListModal.tsx
  src/components/common/Loading.tsx
  src/components/header/GlobalHeader.tsx
  src/components/header/subHeader.tsx
  src/components/members/issue/MemberAddTicket.tsx
  src/components/members/issue/SelectedTicket.tsx
  src/components/schedules/details/CounselingDetail.tsx
  src/components/schedules/details/CounselingRecordFormModal.tsx
  src/components/schedules/form/CounselingForm.tsx
  src/components/schedules/form/PrivateLessonForm.tsx
  src/hooks/utils/useValidation.tsx
  src/pages/Members.tsx
  src/pages/backup/Sample.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#85 [♻refactor] 회원 수정 시 직업 및 방문경로 매핑
  src/components/members/MembersRegister.tsx
  src/components/members/detail/MemberEdit.tsx
Labels: 🔨 Refactor

#87 [✨feat] 회원에게 부여된 수강권 편집 (#86)
  src/apis/membersAPIs.tsx
  src/components/center/ticket/IssuedTicketModal.tsx
  src/components/center/ticket/TicketIssued.tsx
  src/components/members/MemberEditForm.tsx
  src/components/members/MembersForm.tsx
  src/components/members/backup/MemberTicketEditForm.tsx
  src/components/members/backup/Members.tsx
  src/components/members/detail/MemberDetail.tsx
  src/components/members/detail/TicketItem.tsx
  src/components/members/issue/IssueTicketEditForm.tsx
  src/components/members/issue/IssueTicketForm.tsx
  src/components/members/issue/IssueTicketFormComponent.tsx
  src/components/members/issue/MemberAddTicket.tsx
  src/components/members/issue/TicketItem.tsx
  src/hooks/utils/useInput.tsx
  src/pages/Members.tsx
Labels: ✨ Feature

#91 [🐞fix] 뒤로가기 안되는 오류 해결 (#88)
  src/components/center/staff/StaffsList.tsx
  src/components/center/ticket/TicketList.tsx
  src/components/members/list/MemberList.tsx
  src/components/schedules/calendar/Calendar.tsx
  src/components/schedules/calendar/SchedulesHome.tsx
  src/utils/schedules/getDate.tsx
Labels: 🐞 BugFix

#92 [🐞fix] 뒤로가기 안되는 오류 해결 (#88)
  src/components/issuedTickets/IssueTicketFormComponent.tsx
  src/components/members/detail/MemberDetail.tsx
Labels: 🐞 BugFix

#99 [🛠build] 빌드 프로젝트 세팅
  .gitignore
  package-lock.json
  package.json
  src/main.tsx
  vite.config.ts
Labels: 🗿 Chore

#105 [📝Docs] Update README
  README.md
Labels: 📃 Documentation

#106 [📝Docs] Update README
  README.md
Labels: 📃 Documentation

#108 [📝Docs] Update README.md
  README.md
Labels: 📃 Documentation

#109 [📝docs] Update README.md
  README.md
Labels: 📃 Documentation
